services:
  mongo:
    container_name: mongo-container
    image: "mongo:6"
    restart: always
    volumes:
      - ./data:/usr/src/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    image: clean-tdd-api
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-tdd-api/dist
    ports:
      - "5050:5050"
    depends_on:
      - "mongo"
    
